### ISSUE TITLE
Thank you for your work. Can you provide me with the ID of the mscoco dataset?

### ISSUE THREAD

**Issue by yul1998** [LiJiaBei-7/nrccr#4]
![1718783595364](https://github.com/LiJiaBei-7/nrccr/assets/71552069/cbb98e3f-dd5a-4b58-b5e2-18337264e830)

**Comment by LiJiaBei-7** [comment]
链接: https://pan.baidu.com/s/1nKEYP7IIX0dg4WFTNNyeJw?pwd=0707 提取码: 0707

**Comment by yul1998** [comment]
Thanks！
